CrudWebApp/Models/Candidates.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CrudWebApp.Models
{
    public class CandidatesLi
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string? First_Name { get; set; } 

        [Required]
        public string? Last_Name { get; set; } 

        [Required]
        public DateTime Date_Of_Birth { get; set; }

        [Required]
        public int Age { get; set; }

        [Required]
        public string Weight { get; set; }

        [Required]
        public string Height { get; set; }

        [Required]
        public string Hair_Colour { get; set; }

        [Required]
        public DateTime CreatedDateTime { get; set; } = DateTime.Now;


       

        

    }
}

CrudWebApp/Models/ErrorViewModel.cs
namespace CrudWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CrudWebApp/Controllers/CandidateController.cs
using CrudWebApp.Data;
using CrudWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CrudWebApp.Controllers
{
    public class CandidateController : Controller
    {
        private readonly CrudDbContext _db;

        public CandidateController(CrudDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<CandidatesLi> objCandidateList = _db.CandidateInfo;
            return View(objCandidateList);
        }

        //GET

        [HttpGet]
        public IActionResult Add()
        {

            return View();
        }
        //POST

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(CandidatesLi obj)
        {
            if(ModelState.IsValid)
            {
                _db.CandidateInfo.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Candidate added successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
            
        }


        //GET

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var CandidatesLiFromDb = _db.CandidateInfo.Find(id);
            //var CandidatesLiFromFirst = _db.CandidateInfo.FirstOrDefault(u=>u.Id==id);
            //var CandidatesLiFromSingle = _db.CandidateInfo.SingleOrDefault(u=>u.Id==id);

            if (CandidatesLiFromDb == null)
            {
                return NotFound();
            }
            return View(CandidatesLiFromDb);
        }
        //POST

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CandidatesLi obj)
        {
            if (ModelState.IsValid)
            {
                _db.CandidateInfo.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Candidate updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);

        }

        //GET

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var CandidatesLiFromDb = _db.CandidateInfo.Find(id);
            //var CandidatesLiFromFirst = _db.CandidateInfo.FirstOrDefault(u=>u.Id==id);
            //var CandidatesLiFromSingle = _db.CandidateInfo.SingleOrDefault(u=>u.Id==id);

            if (CandidatesLiFromDb == null)
            {
                return NotFound();
            }
            return View(CandidatesLiFromDb);
        }
        //POST

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _db.CandidateInfo.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            
                _db.CandidateInfo.Remove(obj);
                _db.SaveChanges();
            TempData["success"] = "Candidate deleted successfully";
            return RedirectToAction("Index");
            
            

        }
        
    }

}

CrudWebApp/Controllers/HomeController.cs
using CrudWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CrudWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CrudWebApp/Views/Candidate/Add.cshtml
@model CandidatesLi

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Add Candidate
            </h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="First_Name"> First Name</label>
            <input asp-for="First_Name" class= "form-control"/>
            <span asp-validation-for="First_Name" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Last_Name"> Last Name</label>
            <input asp-for="Last_Name" class="form-control" />
            <span asp-validation-for="Last_Name" class="text-danger">Please input your Last Name</span>
        </div>
        

         <div class="mb-3">
            <label  asp-for="Date_Of_Birth">Birth Date</label>
            <input asp-for="Date_Of_Birth" asp-format="{0:yyyy-MM-dd}"
                   class="form-control" placeholder="YYYY-MM-DD" type="text" />
                                                           @*add type="text"*@
            <span asp-validation-for="Date_Of_Birth" class="text-danger"></span>
          </div>

        <div class="mb-3">
            <label asp-for="Age">Age </label>
            <input type="text" id="age" asp-for="Age" readonly="readonly" class="form-control" />
        </div>
       
        <div>
            <button type="submit" class="btn btn-primary" style="width:150px">ADD</button>
            <a asp-controller="Candidate" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to Lists</a>
        </div>


        @if (ViewData["Message"] != null)
        {
            <div class="form-group row">
                <div class="offset-sm-2 col-sm-6">
                    <div class="alert alert- @ViewData["MsgType"]">
                        @Html.Raw(ViewData["Message"])
                    </div>
                </div>
            </div>
        }
    </div>
        
    
		
    
</form>

 @section Scripts{
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script language="javascript">
        $(document).ready(function () {
            $('#Date_Of_Birth')
                .datepicker({   
                    format: 'yyyy-MM-DD',
                    maxDate: '+0d',
                    yearRange: '1900:2025',
                    changeMonth: true,
                    changeYear: true,
                    onSelect: function (value, ui) {
                        var today = new Date(),
                            dob = new Date(value),
                            age = new Date(today - dob).getFullYear() - 1970;

                        $('#age').val(age); 
                    }
                });
        })

    </script>

    
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    
}

CrudWebApp/Views/Candidate/Delete.cshtml
@model CandidatesLi

<form method="post" asp-action="DeletePOST">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Delete Candidate
            </h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="First_Name"> First Name</label>
            <input asp-for="First_Name" readonly="readonly" class= "form-control"/>
        </div>

        <div class="mb-3">
            <label asp-for="Last_Name"> Last Name</label>
            <input asp-for="Last_Name" readonly="readonly" class="form-control" />
        </div>
        

         <div class="mb-3">
            <label  asp-for="Date_Of_Birth">Birth Date</label>
            <input asp-for="Date_Of_Birth" readonly="readonly" asp-format="{0:yyyy-MM-dd}"
                   class="form-control" placeholder="YYYY-MM-DD" type="text" />
                                                           @*add type="text"*@
          </div>

        <div class="mb-3">
            <label asp-for="Age">Age </label>
            <input type="text" id="age" asp-for="Age" readonly="readonly" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="Weight">Weight </label>
            <input type="text" readonly="readonly" asp-for="Weight"  class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="Height">Height </label>
            <input type="text"  readonly="readonly" asp-for="Height"  class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="Hair_Colour">Hair Colour </label>
            <input type="text"  readonly="readonly" asp-for="Hair_Colour"  class="form-control" />
        </div>
       
        <div>
            <button type="submit" class="btn btn-danger" style="width:150px">DELETE</button>
            <a asp-controller="Candidate" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to Lists</a>
        </div>


        @if (ViewData["Message"] != null)
        {
            <div class="form-group row">
                <div class="offset-sm-2 col-sm-6">
                    <div class="alert alert- @ViewData["MsgType"]">
                        @Html.Raw(ViewData["Message"])
                    </div>
                </div>
            </div>
        }
    </div>
        
    
		
    
</form>

 @section Scripts{
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script language="javascript">
        $(document).ready(function () {
            $('#Date_Of_Birth')
                .datepicker({   
                    format: 'yyyy-MM-DD',
                    maxDate: '+0d',
                    yearRange: '1900:2025',
                    changeMonth: true,
                    changeYear: true,
                    onSelect: function (value, ui) {
                        var today = new Date(),
                            dob = new Date(value),
                            age = new Date(today - dob).getFullYear() - 1970;

                        $('#age').val(age); 
                    }
                });
        })

    </script>

    
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    
}

CrudWebApp/Views/Candidate/Edit.cshtml
@model CandidatesLi

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Edit Candidate
            </h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="First_Name"> First Name</label>
            <input asp-for="First_Name" class= "form-control"/>
            <span asp-validation-for="First_Name" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Last_Name"> Last Name</label>
            <input asp-for="Last_Name" class="form-control" />
            <span asp-validation-for="Last_Name" class="text-danger"></span>
        </div>
        

         <div class="mb-3">
            <label  asp-for="Date_Of_Birth">Birth Date</label>
            <input asp-for="Date_Of_Birth" asp-format="{0:yyyy-MM-dd}"
                   class="form-control" placeholder="YYYY-MM-DD" type="text" />
                                                           @*add type="text"*@
            <span asp-validation-for="Date_Of_Birth" class="text-danger"></span>
          </div>

        <div class="mb-3">
            <label asp-for="Age">Age </label>
            <input type="text" id="age" asp-for="Age" readonly="readonly" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="Weight">Weight </label>
            <input type="text" id="weight" asp-for="Weight"  class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="Height">Height </label>
            <input type="text" id="height" asp-for="Height"  class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="Hair_Colour">Hair Colour </label>
            <input type="text" id="colour" asp-for="Hair_Colour"  class="form-control" />
        </div>
       
        <div>
            <button type="submit" class="btn btn-primary" style="width:150px">UPDATE</button>
            <a asp-controller="Candidate" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to Lists</a>
        </div>


        @if (ViewData["Message"] != null)
        {
            <div class="form-group row">
                <div class="offset-sm-2 col-sm-6">
                    <div class="alert alert- @ViewData["MsgType"]">
                        @Html.Raw(ViewData["Message"])
                    </div>
                </div>
            </div>
        }
    </div>
        
    
		
    
</form>

 @section Scripts{
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script language="javascript">
        $(document).ready(function () {
            $('#Date_Of_Birth')
                .datepicker({   
                    format: 'yyyy-MM-DD',
                    maxDate: '+0d',
                    yearRange: '1900:2025',
                    changeMonth: true,
                    changeYear: true,
                    onSelect: function (value, ui) {
                        var today = new Date(),
                            dob = new Date(value),
                            age = new Date(today - dob).getFullYear() - 1970;

                        $('#age').val(age); 
                    }
                });
        })

    </script>

    
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    
}

CrudWebApp/Views/Candidate/Index.cshtml
@model IEnumerable<CandidatesLi>
@{
    ViewData["Title"] = "Index";
}


<div class="container p-3" >
    <div class="row">
        <div class="col-6">
            <h2 class="text-primary"> Candidate List

            </h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Candidate" asp-action="Add" class="btn btn-primary">
              <i class="bi bi-plus-circle"></i> &nbsp; Add New Candidate
            </a>
        </div>
    </div>
    <br /><br />

<table class="table table-bodered table-striped " style="width:100%">
    <thead>
        <tr>
            <th>
                First Name
            </th>
            <th>
                Last Name
            </th>
            <th>
                Date of Birth
            </th>
            <th>
                Age
            </th>
            <th>
                Weight
            </th>
            <th>
                Height
            </th>
            <th>
                Hair Colour
            </th>
            <th></th>
            
        </tr>
    </thead>

<tbody>
    @foreach(var obj in Model)
{
    <tr>
        <td width="30%">
            @obj.First_Name
        </td>
        <td width="30%">
            @obj.Last_Name
        </td>
        <td width="30%">
            @obj.Date_Of_Birth
        </td>
        <td width="10%">
            @obj.Age
            </td>
            <td width="30%">
            @obj.Weight
        </td>
        <td width="30%">
            @obj.Height
        </td>
        <td width="30%">
            @obj.Hair_Colour
        </td>
            <td>
                <div class="w-75 btn-group" role="group">
                    <a asp-controller="Candidate" asp-action="Edit" asp-route-id="@obj.Id"
                    class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i>Edit</a>
                    <a asp-controller="Candidate" asp-action="Delete" asp-route-id="@obj.Id"
                    class="btn btn-danger mx-2"><i class="bi bi-trash-fill"></i>Delete</a>

                </div>
            </td>
        </tr>

}

</tbody>
</table>
</div>

CrudWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">A simple CRUD web app with minimal functionality & EF core</h1>
    <p>LinkedIn<a href="https://www.linkedin.com/in/eberebenny/">Visit</a>.</p>
    <p>Github<a href="https://github.com/tesseractT">Visit</a>.</p>
</div>

CrudWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUDWEBAPP</title>
    <link rel="stylesheet" href="~/css/bootstrapTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CrudWebApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/jquery-ui.min.css"/>



</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">CRUD WEB APP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home
            <span class="visually-hidden">(current)</span>
          </a>
        </li>
        <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Candidate" asp-action="Index">View Candidates</a>

        @*</li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Separated link</a>
          </div>
        </li>*@
      </ul>
      <form class="d-flex">
        <input class="form-control me-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
        
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>
    
    <footer class="footer text-muted bg-dark">
        <div class="container">
            &copy; 2022 - CrudWebApp by Benny - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>

    </footer>
   
        
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>   
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/jquery-ui.min.js"></script>


    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CrudWebApp/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null )
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
    
}
@if(TempData["error"] != null )
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}